select [Appeals].[Id]
      ,[Appeals].[applicant_id]
      ,[Appeals].[registration_date]
      ,[Appeals].[registration_number]
      ,[Appeals].[receipt_source_id]
      ,[Appeals].[phone_number]
      ,[Appeals].[mail]
      ,[Appeals].[enter_number]
      ,[Appeals].[submission_date]
      ,[Appeals].[receipt_date]
      ,[Appeals].[start_date]
      ,[Appeals].[end_date]
      ,[Appeals].[article]
      ,[Appeals].[sender_name]
      ,[Appeals].[sender_post_adrress]
      ,[Appeals].[city_receipt]
      ,[Appeals].[user_id]
      ,[Appeals].[edit_date]
      ,[Appeals].[user_edit_id] 
      ,[ReceiptSources].[name] as [ReceiptSources_name]
from [dbo].[Appeals]
left join [dbo].[ReceiptSources] on [ReceiptSources].[Id] = [Appeals].[receipt_source_id]
where [Appeals].[Id] = @Id

