--declare @DateCalc date = N'2019-10-16', @RDAId int = 0, @RatingId int = 1


SELECT [Id]
      ,[DateCalc]
      ,[Date_Start]
      ,[Date_End]
      ,[RatingId]
      ,[RDAId]
      ,[PreviousPeriod_Total]
      ,[PreviousPeriod_Registered]
      ,[PreviousPeriod_InTheWorks]
      ,[PreviousPeriod_InTest]
      ,[PreviousPeriod_ForRevision]
      ,[PreviousPeriod_Closed]
      ,[CurrentMonth_Total]
      ,[CurrentMonth_Registered]
      ,[CurrentMonth_InTheWorks]
      ,[CurrentMonth_InTest]
      ,[CurrentMonth_ForRevision]
      ,[CurrentMonth_Closed]
      ,[OfThem_Registered]
      ,[OfThem_AtWork]
      ,[OnTest_Done]
      ,[OnTest_Explained]
      ,[OnTest_CannotBeExecutedAtThisTime]
      ,[ResultOfExecution_Done]
      ,[ResultOfExecution_Explained]
      ,[ResultOfExecution_Others]
      ,[ForRevision_All]
      ,[ForRevision_Total]
      ,[ForRevision_1Time]
      ,[ForRevision_2Times]
      ,[ForRevision_3AndMore]
      ,[ViewedByArtist_Total]
      ,[ViewedByArtist_WrongTime]
      ,[PercentClosedOnTime]
      ,[PercentOfExecution]
      ,[PercentOnVeracity]
      ,[IndexOfSpeedToExecution]
      ,[IndexOfSpeedToExplain]
      ,[IndexOfFactToExecution]
      ,[PercentPleasureOfExecution]
      ,[IntegratedMetric_PerformanceLevel]
  FROM [dbo].[Rating_ResultTable]
  where [DateCalc] = N'2019-10-16'
  and [RatingId] = @RatingId
  and ([RDAId] = @RDAId or isnull(@RDAId,0) = 0)
 -- and [RDAId] @GlobalFilter_RDAId