INSERT INTO [CRM_1551_Site_Integration].[dbo].[ApplicantFromSiteAddresses]
           ([ApplicantFromSiteId]
           ,[AddressTypeId]
           ,[Index]
           ,[Country]
           ,[Region]
           ,[District]
           ,[Cityname]
           ,[Streetid]
           ,[StreetName]
           ,[BuildingId]
           ,[BuildingName]
           ,[flat])
     VALUES
           (@applicant_id
           ,@addresstype_id
           ,@index
           ,@country
           ,@region
           ,@district
           ,@cityname
           ,@street_id
           ,@street
           ,@building_id
           ,@building
           ,@flat)