update [dbo].[Rating_ReferenceWeight_IntegratedMetric_PerformanceLevel] set [Date_Start] = @Date_Start
      ,[k1_name] = @k1_name
      ,[k1_value] = @k1_value
      ,[k1_isUse] = @k1_isUse
      ,[k2_name] = @k2_name
      ,[k2_value] = @k2_value
      ,[k2_isUse] = @k2_isUse
      ,[k3_name] = @k3_name
      ,[k3_value] = @k3_value
      ,[k3_isUse] = @k3_isUse
      ,[k4_name] = @k4_name
      ,[k4_value] = @k4_value
      ,[k4_isUse] = @k4_isUse
      ,[k5_name] = @k5_name
      ,[k5_value] = @k5_value
      ,[k5_isUse] = @k5_isUse
      ,[k6_name] = @k6_name
      ,[k6_value] = @k6_value
      ,[k6_isUse] = @k6_isUse
      ,[k7_name] = @k7_name
      ,[k7_value] = @k7_value
      ,[k7_isUse] = @k7_isUse
      ,[formula_id] = @formula_id
      ,[comment] = @comment
      ,[RatingId] = @RatingId
      ,[UpdatedAt] = getutcdate()
      ,[UpdatedUserById] = @UpdatedUserById
where [Id] = @Id