SELECT [Id]
      ,[ApplicantFromSiteId] as [applicant_id]
      ,[DocumentTypeId] as [documenttype_id]
      ,[series]
      ,[documentnumber]
      ,[issuedate]
      ,[validity]
      ,[issued_by]
  FROM [CRM_1551_Site_Integration].[dbo].[ApplicantFromSiteDocuments]
  where ApplicantFromSiteId = @applicant_id